# Generated by Django 6.0 on 2026-04-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_menu_item_id_alter_merch_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='category',
            field=models.CharField(choices=[('COF', 'Coffee'), ('FRA', 'Frappe'), ('KID', 'Starbright Kids'), ('FOO', 'Food'), ('SPE', 'Starbright Specialty Drinks'), ('LOT', 'Lotus plant Power'), ('OTH', 'Other')], default='COF', max_length=3),
        ),
    ]
