# Generated by Django 6.0 on 2026-04-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_menu_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='featured',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
