# Generated by Django 6.0 on 2026-04-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_menu_item_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_item',
            old_name='featured',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='merch_item',
            old_name='featured',
            new_name='is_featured',
        ),
    ]
