# Generated by Django 6.0 on 2026-04-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_featured_menu_item_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
