# Generated by Django 6.0 on 2026-04-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_menu_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='description',
            field=models.TextField(default='No description available for this item.'),
        ),
    ]
