# Generated by Django 5.2.7 on 2026-04-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_menu_item_id_alter_merch_item_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu_Item',
        ),
        migrations.DeleteModel(
            name='Merch_Item',
        ),
    ]
