# Generated by Django 5.2.7 on 2026-04-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_menu_item_delete_merch_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='para_three',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='para_two',
            field=models.TextField(blank=True, default=None),
        ),
    ]
