# Generated by Django 5.2.7 on 2026-04-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='poster',
            field=models.CharField(max_length=20),
        ),
    ]
