# Generated by Django 5.2.7 on 2026-04-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_newsletter_id_alter_review_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(),
        ),
    ]
